development:
  adapter: postgresql
  encoding: unicode
  database: npr_bumps_development
  pool: 5
  username: npr_bumps
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: npr_bumps_test
  pool: 5
  username: npr_bumps
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: npr_bumps_production
  pool: 5
  username: npr_bumps
  password:
